#activity 7
utica_tavg <- read.csv("/Users/emmastuart/Documents/USW00094794_tavg.csv")
str(utica_tavg)
mean(utica_tavg$tavg2[utica_tavg$year == "1998"], na.rm = TRUE)
averagetemp <- aggregate(utica_tavg$tavg2, by = list(utica_tavg$year), FUN = "mean", na.rm = TRUE)
utica_tavg$year <- as.factor(utica_tavg$year)
mean(utica_tavg$tavg2[utica_tavg$year == "1998"])
mean(utica_tavg$tavg2)
utica_tavg <- read.csv("/Users/emmastuart/Documents/USW00094794_tavg.csv")
mean(utica_tavg$tavg2[utica_tavg$year == "1998"])
utica_tavg <- read.csv("/Users/emmastuart/Documents/USW00094794_tavg.csv")
mean(utica_tavg$tavg2[utica_tavg$year == "1998"], )
str(utica_tavg)
utica_tavg$tavg2 <- as.numeric(utica_tavg$tavg2)
mean(utica_tavg$tavg2[utica_tavg$year == "1998"], na.rm = TRUE)
mean(utica_tavg$tavg2[utica_tavg$year == "1998"])
summary(utica_tavg)
