utica_tavg <- read.csv("/Users/emmastuart/Documents/Utica_tavg.csv")
utica_tavg$Year <- as.factor(utica_tavg$Year)
utica_tavg$Tavg <- as.numeric(utica_tavg$Tavg)
averagetemp_U <- aggregate(utica_tavg$Tavg, by = list(utica_tavg$Year), FUN = "mean", na.rm = TRUE)
colnames(averagetemp_U) <- c("Year", "MAAT")
